/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatSolarizedDarkIJTheme;
import com.mycompany.views.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author doria
 */
public class Dashboard extends javax.swing.JFrame {
    

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        initStyes();
        initContenido();
        
    }
    private void initContenido() {
        ShowJPanel(new Bienvenida());
    }
    public static void ShowJPanel(JPanel p){
        p.setSize(750, 430);
        p.setLocation(0,0);
        Contenido.removeAll();
        Contenido.add(p, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Devoluciones1 = new javax.swing.JButton();
        Fondo = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Msg = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        Bienvenida = new javax.swing.JButton();
        Usuarios = new javax.swing.JButton();
        Libros = new javax.swing.JButton();
        Historial = new javax.swing.JButton();
        Prestamos = new javax.swing.JButton();
        Devoluciones = new javax.swing.JButton();
        Dispo = new javax.swing.JButton();
        Contenido = new javax.swing.JPanel();

        Devoluciones1.setBackground(new java.awt.Color(0, 102, 102));
        Devoluciones1.setText("Devoluciones");
        Devoluciones1.setAlignmentX(2.0F);
        Devoluciones1.setBorder(null);
        Devoluciones1.setBorderPainted(false);
        Devoluciones1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Devoluciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Devoluciones1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        Encabezado.setBackground(new java.awt.Color(0, 102, 102));

        Msg.setText("Sistema de gestión de biblioteca");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO_UTSEM.png"))); // NOI18N

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.setBackground(new java.awt.Color(0, 153, 153));

        Bienvenida.setBackground(new java.awt.Color(0, 102, 102));
        Bienvenida.setText("Bienvenida");
        Bienvenida.setBorder(null);
        Bienvenida.setBorderPainted(false);
        Bienvenida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BienvenidaActionPerformed(evt);
            }
        });

        Usuarios.setBackground(new java.awt.Color(0, 102, 102));
        Usuarios.setText("Usuarios");
        Usuarios.setBorder(null);
        Usuarios.setBorderPainted(false);
        Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });

        Libros.setBackground(new java.awt.Color(0, 102, 102));
        Libros.setText("Libros");
        Libros.setBorder(null);
        Libros.setBorderPainted(false);
        Libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrosActionPerformed(evt);
            }
        });

        Historial.setBackground(new java.awt.Color(0, 102, 102));
        Historial.setText("Historial");
        Historial.setBorder(null);
        Historial.setBorderPainted(false);
        Historial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });

        Prestamos.setBackground(new java.awt.Color(0, 102, 102));
        Prestamos.setText("Prestamos");
        Prestamos.setBorder(null);
        Prestamos.setBorderPainted(false);
        Prestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestamosActionPerformed(evt);
            }
        });

        Devoluciones.setBackground(new java.awt.Color(0, 102, 102));
        Devoluciones.setText("Devoluciones");
        Devoluciones.setAlignmentX(2.0F);
        Devoluciones.setBorder(null);
        Devoluciones.setBorderPainted(false);
        Devoluciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolucionesActionPerformed(evt);
            }
        });

        Dispo.setBackground(new java.awt.Color(0, 102, 102));
        Dispo.setText("Disponibilidad");
        Dispo.setBorder(null);
        Dispo.setBorderPainted(false);
        Dispo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Dispo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Libros, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Historial, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Dispo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Libros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(Historial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Contenido.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolucionesActionPerformed
        ShowJPanel(new Devoluciones());
    }//GEN-LAST:event_DevolucionesActionPerformed

    private void PrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestamosActionPerformed
        ShowJPanel(new Prestamos());
    }//GEN-LAST:event_PrestamosActionPerformed

    private void BienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BienvenidaActionPerformed
        ShowJPanel(new Bienvenida());
    }//GEN-LAST:event_BienvenidaActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        ShowJPanel(new Usuarios());
    }//GEN-LAST:event_UsuariosActionPerformed

    private void LibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrosActionPerformed
        ShowJPanel(new Libros());
    }//GEN-LAST:event_LibrosActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        ShowJPanel( new Historial());
    }//GEN-LAST:event_HistorialActionPerformed

    private void Devoluciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Devoluciones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Devoluciones1ActionPerformed

    private void DispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispoActionPerformed
        ShowJPanel(new Disponibilidad());
    }//GEN-LAST:event_DispoActionPerformed

    /**
     * @param args the command line arguments
     */
    //myTitleLabel.putClientProperty( "FlatLaf.styleClass", "h1" );
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatCyanLightIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    private void initStyes() {
        Msg.putClientProperty( "FlatLaf.styleClass", "h00" );
        Msg.setForeground(Color.white);
        Bienvenida.setForeground(Color.white);
        Devoluciones.setForeground(Color.white);
        Historial.setForeground(Color.white);
        Prestamos.setForeground(Color.white);
        Usuarios.setForeground(Color.white);
        Libros.setForeground(Color.white);
        Dispo.setForeground(Color.white);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bienvenida;
    private static javax.swing.JPanel Contenido;
    private javax.swing.JButton Devoluciones;
    private javax.swing.JButton Devoluciones1;
    private javax.swing.JButton Dispo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Historial;
    private javax.swing.JButton Libros;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Msg;
    private javax.swing.JButton Prestamos;
    private javax.swing.JButton Usuarios;
    // End of variables declaration//GEN-END:variables


    
}
