/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.biblioteca.DAOLibrosIMPL;
import com.mycompany.biblioteca.DAOPrestamosIMPL;
import com.mycompany.interfaces.DAOLibros;
import com.mycompany.interfaces.DAOPrestamos;
import com.mycompany.utils.Utils;

/**
 *
 * @author doria
 */
public class Disponibilidad extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenida
     */
    public Disponibilidad() {
        initComponents();
        initStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        libId = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(668, 375));
        setRequestFocusEnabled(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(668, 375));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamos.png"))); // NOI18N
        jLabel1.setText("Disponibilidad");

        button.setBackground(new java.awt.Color(0, 102, 102));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Registrar");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Libro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(223, 223, 223))
                            .addComponent(libId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(462, 462, 462)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(385, 385, 385))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String libro = libId.getText();
        try {
            if (libro.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                libId.requestFocus();
                return;
            } else if (!Utils.isNumeric(libro)) {
                javax.swing.JOptionPane.showMessageDialog(this, "El ID del libro debe ser números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                libId.requestFocus();
                return;
            }
            com.mycompany.models.Prestamos prestamo = new com.mycompany.models.Prestamos();
            prestamo.setCod_libro(libro);
            DAOLibros daoBooks = new DAOLibrosIMPL();

            com.mycompany.models.Libros currentBook = daoBooks.getLibroById(Integer.parseInt(libro));
            if (currentBook == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún libro con ese ID. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                libId.requestFocus();
                return;
            }
            DAOPrestamos daoDisp = new DAOPrestamosIMPL();

            com.mycompany.models.Prestamos currentDisp = daoDisp.getDispById(Integer.parseInt(libro));
            if (currentDisp != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Libro No disponible. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                libId.requestFocus();
                return;
            } else if(currentDisp == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Libro disponible.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al consultar la disponibilidad. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }

    private void initStyles() {
        jLabel1.putClientProperty("FlatLaf.styleClass", "h0");

        jLabel2.putClientProperty("FlatLaf.styleClass", "large");
        libId.putClientProperty("JTextField.placeholderText", "Ingrese el ID de Libro");
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField libId;
    // End of variables declaration//GEN-END:variables

}
