/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.biblioteca.DAOUsuariosIMPL;
import com.mycompany.interfaces.DAOUsuarios;

/**
 *
 * @author doria
 */
public class SUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenida
     */
    boolean isEdition = false;
    com.mycompany.models.Usuarios userEdition;
    public SUsuarios() {
        initComponents();
        initStyles();
    }
    public SUsuarios(com.mycompany.models.Usuarios user) {
        initComponents();
        isEdition = true;
        userEdition = user;
        initStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Poblacion = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Albl = new javax.swing.JLabel();
        Apellidos = new javax.swing.JTextField();
        Dlbl = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Domlbl = new javax.swing.JLabel();
        Domicilio = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        Polbl = new javax.swing.JLabel();
        Nlbl = new javax.swing.JLabel();
        Flbl = new javax.swing.JLabel();
        FNacimiento = new javax.swing.JTextField();
        Prlbl = new javax.swing.JLabel();
        Provincia = new javax.swing.JTextField();
        button = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(668, 375));
        setRequestFocusEnabled(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(668, 375));

        Poblacion.setToolTipText("");

        Albl.setText("Apellidos");

        Dlbl.setText("DNI");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        Domlbl.setText("Domicilio");

        Domicilio.setToolTipText("");

        title.setText("Registrar nuevo Usuario");

        Polbl.setText("Poblacion");

        Nlbl.setText("Nombre");

        Flbl.setText("Fecha de nacimiento(AAAA-MM-DD)");

        Prlbl.setText("Provincia");

        Provincia.setToolTipText("");

        button.setBackground(new java.awt.Color(0, 102, 102));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Registrar");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Flbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(186, 186, 186))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FNacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Nlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(223, 223, 223))
                                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Albl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(182, 182, 182))
                                    .addComponent(Apellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Dlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(180, 180, 180))
                                    .addComponent(DNI, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(68, 68, 68)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Domicilio)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Domlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(220, 220, 220))
                            .addComponent(Poblacion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Polbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(218, 218, 218))
                            .addComponent(Provincia)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Prlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(218, 218, 218))
                            .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(553, 553, 553))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Albl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Dlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Flbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Domlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Polbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Prlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String nombre = Nombre.getText();
        String apellido = Apellidos.getText();
        String dni = DNI.getText();
        String domicilio = Domicilio.getText();
        String provincia = Provincia.getText();
        String f_nac = FNacimiento.getText();
        String poblacion = Poblacion.getText();
        if (nombre.isEmpty() || apellido.isEmpty() || dni.isEmpty() || domicilio.isEmpty() || provincia.isEmpty()||f_nac.isEmpty()||poblacion.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            Nombre.requestFocus();
            return;
        }
        com.mycompany.models.Usuarios user = isEdition ? userEdition : new com.mycompany.models.Usuarios();
        user.setNombre(nombre);
        user.setApellidos(apellido);
        user.setDNI(dni);
        user.setDomicilio(domicilio);
        user.setProvincia(provincia);
        user.setF_Nacimiento(f_nac);
        user.setPoblacion(poblacion);
        try{
            DAOUsuarios dao = new DAOUsuariosIMPL();
            if (!isEdition) {
                dao.registrar(user);
            } else {
                dao.modificar(user);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Usuario " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            if (!isEdition) {
                Nombre.setText("");
                Apellidos.setText("");
                DNI.setText("");
                Domicilio.setText("");
                Provincia.setText("");
                FNacimiento.setText("");
                Poblacion.setText("");
            }
        }catch(Exception e){
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el usuario. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Albl;
    private javax.swing.JTextField Apellidos;
    private javax.swing.JTextField DNI;
    private javax.swing.JLabel Dlbl;
    private javax.swing.JTextField Domicilio;
    private javax.swing.JLabel Domlbl;
    private javax.swing.JTextField FNacimiento;
    private javax.swing.JLabel Flbl;
    private javax.swing.JLabel Nlbl;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Poblacion;
    private javax.swing.JLabel Polbl;
    private javax.swing.JLabel Prlbl;
    private javax.swing.JTextField Provincia;
    private javax.swing.JButton button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void initStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h0");
        Albl.putClientProperty("FlatLaf.styleClass", "large");
        Dlbl.putClientProperty("FlatLaf.styleClass", "large");
        Domlbl.putClientProperty("FlatLaf.styleClass", "large");
        Flbl.putClientProperty("FlatLaf.styleClass", "large");
        Nlbl.putClientProperty("FlatLaf.styleClass", "large");
        Polbl.putClientProperty("FlatLaf.styleClass", "large");
        Prlbl.putClientProperty("FlatLaf.styleClass", "large");
        Nombre.putClientProperty("JTextField.placeholderText", "Ingrese el nombre de usuario");
        Apellidos.putClientProperty("JTextField.placeholderText", "Ingrese el apellido del usuario");
        DNI.putClientProperty("JTextField.placeholderText", "Ingrese el DNI del usuario");
        Domicilio.putClientProperty("JTextField.placeholderText", "Ingrese el domicilio del usuario");
        Provincia.putClientProperty("JTextField.placeholderText", "Ingrese la provincia del usuario");
        Poblacion.putClientProperty("JTextField.placeholderText", "Ingrese la poblacion del usuario");
        FNacimiento.putClientProperty("JTextField.placeholderText", "Ingrese la fecha en el formato AAAA-MM-DD");
        if (isEdition) {
            title.setText("Editar Usuario");
            button.setText("Guardar");

            if (userEdition != null) {
                Nombre.setText(userEdition.getNombre());
                Apellidos.setText(userEdition.getApellidos());
                DNI.setText(userEdition.getDNI());
                Domicilio.setText(userEdition.getDomicilio());
                Provincia.setText(userEdition.getProvincia());
                FNacimiento.setText(userEdition.getF_Nacimiento());
                Poblacion.setText(userEdition.getPoblacion());
            }
        }
    }
}
